#!/bin/bash

# Firebase Setup Helper for ReCAPTCHA Bypass
# This script provides alternative ways to setup admin user and rooms

echo "🚀 Firebase Setup Helper"
echo "========================"
echo ""
echo "If you're getting 'blocked due to unusual activity' error:"
echo ""
echo "Option 1: Wait 15-30 minutes and try again"
echo "Option 2: Use a different email (test.user@example.com)"
echo "Option 3: Create user from Firebase Console directly"
echo "Option 4: Use Web Dashboard instead of mobile app"
echo ""
echo "========================"
echo ""
echo "✅ QUICK SETUP CHECKLIST:"
echo ""
echo "Step 1: Firebase Console > Authentication"
echo "  Create user: test.user@example.com / Test@12345"
echo ""
echo "Step 2: Firebase Console > Firestore > Collections > users"
echo "  Add document with:"
echo "  - Document ID: (paste User UID from step 1)"
echo "  - role: 'admin'"
echo "  - email: 'test.user@example.com'"
echo "  - name: 'Test User'"
echo ""
echo "Step 3: Try login with: test.user@example.com / Test@12345"
echo ""
echo "If still blocked:"
echo "  - Clear app cache: Settings > Apps > Bookify Rooms > Storage > Clear Cache"
echo "  - Uninstall and reinstall app"
echo "  - Or wait 1 hour for Firebase to unblock"
echo ""
